exports.META = { 
  PAYSTACK_SERVICE: "paystack", 
  FULTTER_WAVE_SERVICE: "flutterwave",
  MAIL:'mail-service',
  AUTH: "authentication",
  ACCOUNT: "account-service",
  INVITATION: "invitation-service",
  ITEM: "item",
  CLOUDINARY: "cloudinary", 
  PAYMENT:"payment",
  KYC:"kyc",
  STORE: "store",
  SUBSCRIPTION: "subscription",
  NOTIFY: "notification",
  PREFERENCE: "preference",
  CHAT: "chat",
  TICKET: "ticket",
  FAQ: "FAQ",
  
}

exports.ERROR_FIELD = {
  INVALID_EMAIL: "Email is Invalid",
  JWT_EXPIRED: "jwt expired",
  EXPIRED_TOKEN: "Token has expired",
  NOT_FOUND: "No Record Found",
  ACCOUNT_NOT_FOUND: "Account was not found",
  INVALID_LINK: "Invalid Link",
  INVITE_EXPIRED: "Invitation have expire",
  INVALID_INVITE: "Invite link is invalid",
  REG_FAILED: "Registration Mail Failed",
  INVALID_OTP: "Invalid OTP",
  INVALID_TOKEN: "Invalid Token",
  TOKEN_NOT_FOUND: "Token not found", 
};
